### ISSUE TITLE
Dependency on LittlevGL v6.0

### ISSUE THREAD

**Issue by ajithpv** [kaiakz/lv_gui_designer#7]
Hi,

First and foremost, I'm really happy to see a GUI designer for the LittlevGL. This is the most awaited feature from many of us.
I have see the below line in the README:
`lv_gui_designer is very dependent on LittlevGL v6.0:`

Hence, I would like to know whether it will work only on the LittlevGL v6.0 or backward and/or forward compatibility is planned for the designer :thinking:

**Comment by embeddedt** [comment]
It's very likely to not support any version before 6.0. However, versions after 6.0 should be supported.

**Comment by kaiakz** [comment]
Hello. Because `lv_gui_designer` use the `event`(Only after v6.0 version support). Well, if we don't use the v6.0 feature, maybe lv_gui_designer can work on v5.x. For v5.x also supports `drag` and `btn signal`.

**Comment by embeddedt** [comment]
`lv_micropython` was significantly improved in v6.0. I wouldn't suggest going back to the older version - I think it had some limitations that could only be addressed in LittlevGL 6.0.

**Comment by ajithpv** [comment]
Thank you @embeddedt , @kaiakz for the valuable feedback :+1:
